application: babbledrive
version: dev
runtime: python
api_version: 1

inbound_services:
- warmup

handlers:
- url: /static/doc
  static_dir: static/doc
  expiration: 28d

- url: /static/data
  static_dir: static/data
  expiration: 28d

- url: /static
  static_dir: static
  expiration: 14d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 28d

- url: /
  script: index.py
